name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-autobuild
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests
    - name: Build Documentation
      run: |
        cd docs
        make html
    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/_build/html
    - name: Security Check
      run: |
        pip install safety
        safety check
